baseurl             = "https://www.cs.toronto.edu/~muuo/"
#baseurl             = "http://localhost"
builddrafts         = false
canonifyurls        = true
contentdir          = "content"
languageCode        = "en-US"
layoutdir           = "layouts"
publishdir          = "public"
theme               = "cocoa"
author              = "Muuo Wambua"
title               = "Muuo Wambua"
pygmentsuseclasses  = true
pluralizelisttitles = false

[permalinks]
writing  = "writing/:slug/"

[[menu.main]]
name                   = "Writing"
weight                 = -120
identifier             = "writing"
url                    = "writing/"

[[menu.main]]
name                   = "Publications"
weight                 = -110
identifier             = "publications"
url                    = "publications/"


[params]
include_rss            = true                          # include RSS <link> tag in <head> and show RSS icon
latestpostscount       = 5                             # how many posts to display on the home page
i18n_flags             = false                         # whether to display small country flags for available translations
author                 = "Muuo Wambua"
cachebuster            = true                          # add the current unix timestamp in query string for cache busting css assets
dateform               = "Jan 2, 2006"
dateformfull           = "Mon Jan 2 2006 15:04:05 EDT"
description            = "I am... so I think...?"
email                  = "muuo [at] cs [dot] toronto [dot] edu"
#extracssfiles          = [ "/css/override.css" ]       # In your `static` directory, add/remove files as necessary.
#faviconfile            = "img/favicon.ico"
github                 = "//github.com/muuo"
#instagram              = "//instagram.com/muuowambua"
unsplash               = "//unsplash.com/muuo"
writing                = "//muuo.me"
#keybase                = "//keybase.io/muuo"
lang                   = "en"
linkedin               = "//linkedin.com/in/muuo"
noshowreadtime         = false                         # if true, don't show "<x> minutes read" in posts
selfintro              = "Computational Linguist, Engineer & Human in the rough." # appears in the site header when set to a non-empty string
#twitter                = "//twitter.com/x2a_io"

highlightjs            = true
# highlightjslanguages = ["go"]                        # additional languages not included in the "common" set
# highlightjsStyle     = "darcula"

avatar = "img/profile.jpg" # path to image in static dir e.g img/avatar.png (do not use in the same time as gravatar)
